const TYPES = {
    SET_ERROR_MESSAGE: Symbol("SET_ERROR_MESSAGE"),
    SET_EMAIL_ERROR_MESSAGE: Symbol("SET_EAMIL_ERROR_MESSAGE"),
    SET_FIRSTNAME_ERROR_MESSAGE: Symbol("SET_FIRSTNAME_ERROR_MESSAGE"),
    SET_LASTNAME_ERROR_MESSAGE: Symbol("SET_LASTNAME_ERROR_MESSAGE"),
    SET_PASSWORD_ERROR_MESSAGE: Symbol("SET_PASSWORD_ERROR_MESSAGE"),
    SET_IS_ADMIN: Symbol("SET_IS_ADMIN"),
    SET_IS_AUTH: Symbol("SET_IS_AUTH"),
    SET_USER: Symbol("SET_USER")
};

export default TYPES;
